# Generated by Django 4.2.3 on 2023-09-09 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pechera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pechera', models.CharField(max_length=100, unique=True)),
                ('fecha_fabricacion', models.DateTimeField()),
                ('talla', models.IntegerField()),
                ('cantidad_lavados', models.IntegerField(default=0)),
                ('observaciones', models.CharField(max_length=500)),
            ],
        ),
    ]
