# Generated by Django 4.2.3 on 2023-09-09 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pechera',
            name='fecha_fabricacion',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='pechera',
            name='talla',
            field=models.CharField(max_length=1),
        ),
    ]
