# Generated by Django 4.2.6 on 2023-10-27 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_pechera_fecha_fabricacion_alter_pechera_talla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pechera',
            name='fecha_fabricacion',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='pechera',
            name='talla',
            field=models.CharField(max_length=5),
        ),
    ]
