# Generated by Django 4.2.6 on 2023-10-28 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_pechera_fecha_fabricacion_alter_pechera_talla'),
    ]

    operations = [
        migrations.AddField(
            model_name='pechera',
            name='planta',
            field=models.CharField(choices=[('Planta1', 'Planta 1'), ('Planta2', 'Planta 2'), ('Planta3', 'Planta 3')], default='Planta1', max_length=50),
        ),
    ]
