# Generated by Django 4.2.6 on 2023-10-28 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_pechera_planta'),
    ]

    operations = [
        migrations.AddField(
            model_name='pechera',
            name='parameters',
            field=models.CharField(choices=[('1', 'Perfectas condiciones'), ('2', 'Ligermante desgastanda'), ('3', 'Desgastada'), ('4', 'Eliminar')], default=1, max_length=50),
        ),
        migrations.AlterField(
            model_name='pechera',
            name='planta',
            field=models.CharField(choices=[('Planta1', 'Salmonera 1'), ('Planta2', 'Slamonera 2'), ('Planta3', 'Salmonera 3')], default='Planta1', max_length=50),
        ),
    ]
