# Generated by Django 4.2.6 on 2023-10-30 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_pechera_parameters'),
    ]

    operations = [
        migrations.AddField(
            model_name='pechera',
            name='indice_microbiologico',
            field=models.CharField(choices=[('si', 'Sí'), ('no', 'No')], default='si', max_length=2, verbose_name='Índice Microbiológico'),
        ),
    ]
