# Generated by Django 4.2.6 on 2023-11-09 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_pechera_indice_microbiologico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pechera',
            name='planta',
            field=models.CharField(choices=[('Planta1', 'ABICK S.A'), ('Planta2', 'CONTINENTALES SPA'), ('Planta3', 'CUTTER S.A'), ('Planta4', 'OCEAN BLUE SPA'), ('Planta5', 'PESQUERA DEL MAR ANTARTICO S.A'), ('Planta6', 'PROCESOS FILETES DEL SUR SPA'), ('Planta7', 'RIO YELCHO SPA'), ('Planta8', 'RIO BLANCO')], default='Planta1', max_length=50),
        ),
    ]
