# Generated by Django 4.2.6 on 2023-11-09 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_pechera_planta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pechera',
            name='indice_microbiologico',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='si', max_length=2, verbose_name='Índice Microbiológico'),
        ),
    ]
