# Generated by Django 4.2.6 on 2023-11-09 23:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_pechera_indice_microbiologico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pechera',
            name='indice_microbiologico',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=2, verbose_name='Índice Microbiológico'),
        ),
        migrations.AlterField(
            model_name='pechera',
            name='parameters',
            field=models.CharField(choices=[('1', 'Nuevo'), ('2', 'Perfectas condiciones'), ('3', 'Ligermante desgastanda'), ('4', 'Desgastada'), ('5', 'Eliminar')], default='1', max_length=50),
        ),
        migrations.CreateModel(
            name='CambioPechera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cambio', models.DateTimeField(default=django.utils.timezone.now)),
                ('campo_modificado', models.CharField(max_length=100)),
                ('valor_anterior', models.CharField(max_length=255)),
                ('valor_nuevo', models.CharField(max_length=255)),
                ('pechera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pechera')),
            ],
        ),
    ]
