# Generated by Django 4.2.6 on 2023-11-09 23:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0012_historialcambio_alter_pechera_indice_microbiologico_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CambiosPechera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField()),
                ('pechera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pechera')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='HistorialCambio',
        ),
    ]
