# Generated by Django 4.2.6 on 2023-11-09 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_cambiospechera_delete_historialcambio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CambiosPechera',
        ),
    ]
