# Generated by Django 4.2.6 on 2023-11-10 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_pechera_historial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pechera',
            name='observaciones',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
