# Generated by Django 5.0.2 on 2024-03-02 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_pechera_observaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='pechera',
            name='fecha_lavado',
            field=models.DateField(null=True),
        ),
    ]
