# Generated by Django 5.0.2 on 2024-03-13 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_pechera_fecha_lavado_alter_pechera_planta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pechera',
            name='fecha_lavado',
        ),
    ]
