# Generated by Django 5.0.2 on 2024-03-17 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_remove_pechera_fecha_lavado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lavado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_lavado', models.CharField(max_length=100, unique=True)),
                ('fecha_lavado', models.DateField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='pechera',
            name='parameters',
            field=models.CharField(choices=[('1', 'Nuevo'), ('2', 'Perfectas condiciones'), ('3', 'Ligermante desgastanda'), ('4', 'Desgastada')], default='1', max_length=50),
        ),
    ]
