# Generated by Django 5.0.2 on 2024-03-17 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_lavado_alter_pechera_parameters'),
    ]

    operations = [
        migrations.AddField(
            model_name='lavado',
            name='id_pechera',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
