# Generated by Django 5.0.2 on 2024-04-23 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_remove_lavado_id_alter_lavado_id_lavado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id_planta', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
