# Generated by Django 5.0.2 on 2024-04-23 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_remove_pechera_planta_alter_pechera_id_planta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pechera',
            old_name='id_planta',
            new_name='planta',
        ),
    ]
